from django.conf.urls import url
from . import views

app_name = 'mysite'

urlpatterns = [
    url(r'^home/$', views.index, name='home'),
url(r'^$', views.index, name='home1'),
    #(r'^email/$', views.email, name='email'),
    url(r'^boarder/$', views.boarder, name='boarder'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^announcement/$', views.announcement, name='announcement'),
url(r'^blog/$', views.blog, name='blog'),
    url(r'^aboutus/$', views.aboutus, name='aboutus'),
    url(r'^award/$', views.award, name='award'),
    url(r'^printer/$', views.printer, name='printer'),
    url(r'^messmenu/$', views.messmenu, name='messmenu'),
url(r'^canteenmenu/$', views.canteenmenu, name='canteenmenu'),
    url(r'^addmessmenu/$', views.addmessmenu, name='addmessmenu'),
url(r'^addcanteenmenu/$', views.addcanteenmenu, name='addcanteenmenu'),
    #url(r'^home/$', views.index, name='index'),
    #url(r'^publications/$', views.publications, name='publications'),
    url(r'^deleteannouncement/(?P<pk>[0-9]+)/$', views.deleteannouncement, name='deleteannouncement'),
    url(r'^deletemessmenu/(?P<pk>[0-9]+)/$', views.deletemessmenu, name='deletemessmenu'),
url(r'^deletecanteenmenu/(?P<pk>[0-9]+)/$', views.deletecanteenmenu, name='deletecanteenmenu'),
    url(r'^deleteboarder/(?P<pk>[0-9]+)/$', views.deleteboarder, name='deleteboarder'),
    url(r'^deleteaward/(?P<pk>[0-9]+)/$', views.deleteaward, name='deleteaward'),
    url(r'^deletefile/(?P<pk>[0-9]+)/$', views.deletefile, name='deletefile'),
    url(r'^upvote/(?P<pk>[0-9]+)/$', views.upvote, name='upvote'),
    url(r'^downvote/(?P<pk>[0-9]+)/$', views.downvote, name='downvote'),        
    # url(r'^deleteexperience/(?P<pk>[0-9]+)/$', views.deleteexperience, name='deleteexperience'),
    # # url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    # # url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^createabout/$', views.createabout, name='createabout'),
    url(r'^clearall/$', views.del_database, name='clearall'),
    url(r'^clearallp/$', views.delprints, name='clearallp'),
    url(r'^createprinter/$', views.createprinter, name='createprinter'),
    url(r'^notes/$', views.notes, name='notes'),
    url(r'^deleteforprinter/(?P<pk>[0-9]+)/$', views.deleteforprinter, name='deleteforprinter'),
    url(r'^pay/$', views.pay, name='pay'),
    url(r'^notesupload/$', views.notesupload, name='notesupload'),   
    # url(r'^editabout/$', views.editabout, name='editabout'),
    # url(r'^aboutto/(?P<user_name>.*)/$',views.aboutto,name='aboutto'),
    # url(r'^todolist/$', views.todolist, name='todolist'),
    # url(r'^createeducation/$', views.createeducation, name='createeducation'),
    # url(r'^education/$', views.education, name='education'),
    # url(r'^teaching/$', views.teaching, name='teaching'),
    url(r'^addannouncement',views.addannouncement,name="addannouncement"),
    url(r'^addboarder',views.addboarder,name="addboarder"),
    url(r'^addaward',views.addaward,name="addaward"),
    url(r'^registerprinter/',views.registerprinter,name="registerprinter"),
    url(r'^getprints/',views.getprints,name="getprints"),
    # url(r'^createexperience/$', views.createexperience, name='createeducation'),
    # url(r'^createtodo/$', views.createtodo, name='createtodo'),
    # url(r'^experience/$', views.experience, name='education'),
    # url(r'^deletetodo/(?P<pk>[0-9]+)/$', views.deletetodo, name='deletetodo'),
    # url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    # url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    # url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    # url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
 url(r'^upload/$', views.upload_file, name='upload'),

]